import { css } from 'lit';

export default css`:root {
  --size-stack-xs: 4rempx;
  --size-stack-sm: 8rempx;
  --size-stack-md: 16rempx;
  --size-stack-lg: 32rempx;
  --size-stack-xl: 64rempx;
  --spacing-inline-sm-top: 0;
  --spacing-inline-sm-right: 8px;
  --spacing-inline-sm-bottom: 0;
  --spacing-inline-sm-left: 8px;
  --spacing-inline-md-top: 0;
  --spacing-inline-md-right: 16px;
  --spacing-inline-md-bottom: 0;
  --spacing-inline-md-left: 16px;
  --spacing-inline-lg-top: 0;
  --spacing-inline-lg-right: 32px;
  --spacing-inline-lg-bottom: 0;
  --spacing-inline-lg-left: 32px;
  --spacing-inset-sm-top: 8px;
  --spacing-inset-sm-right: 0;
  --spacing-inset-sm-bottom: 8px;
  --spacing-inset-sm-left: 0;
  --spacing-inset-md-top: 16px;
  --spacing-inset-md-right: 0;
  --spacing-inset-md-bottom: 16px;
  --spacing-inset-md-left: 0;
  --spacing-inset-lg-top: 32px;
  --spacing-inset-lg-right: 0;
  --spacing-inset-lg-bottom: 32px;
  --spacing-inset-lg-left: 0;
  --border-sm-stroke-align: inside;
  --border-sm-dash-pattern: ;
  --border-sm-stroke-cap: none;
  --border-sm-stroke-join: miter;
  --border-sm-stroke-miter-limit: 4;
  --border-sm-stroke-weight: 1px;
  --border-sm-stroke: rgba(196, 196, 196, 1);
  --radius-sm-radius-type: mixed;
  --radius-sm-radii-top-left: 0;
  --radius-sm-radii-top-right: 0;
  --radius-sm-radii-bottom-right: 0;
  --radius-sm-radii-bottom-left: 0;
  --radius-sm-smoothing: 0;
  --radius-md-radius: 60px;
  --radius-md-radius-type: single;
  --radius-md-radii-top-left: 60px;
  --radius-md-radii-top-right: 60px;
  --radius-md-radii-bottom-right: 60px;
  --radius-md-radii-bottom-left: 60px;
  --radius-md-smoothing: 0;
  --radius-lg-radius: 100px;
  --radius-lg-radius-type: single;
  --radius-lg-radii-top-left: 100px;
  --radius-lg-radii-top-right: 100px;
  --radius-lg-radii-bottom-right: 100px;
  --radius-lg-radii-bottom-left: 100px;
  --radius-lg-smoothing: 0;
  --color-debug: #c4c4c4;
  --color-primary-default-base: #0099ff; /* primary default base */
  --color-primary-default-contrast: #ffffff; /* primary default contrast */
  --color-primary-hover-base: #f7b538; /* primary hover base */
  --color-primary-hover-contrast: #7353ba; /* primary hover contrast */
  --color-primary-active-base: #7353ba; /* primary active base */
  --color-primary-active-contrast: #f7b538; /* primary active contrast */
  --color-secondary-default-base: #ffffff; /* secondary default base */
  --color-secondary-default-contrast: #7353ba; /* secondary default contrast */
  --color-secondary-hover-base: #ffffff; /* secondary hover base */
  --color-secondary-hover-contrast: #f7b538; /* secondary hover contrast */
  --color-secondary-active-base: #f7b538; /* secondary active base */
  --color-secondary-active-contrast: #7353ba; /* secondary active contrast */
  --color-accent-base: #e74136; /* accent base */
  --color-accent-contrast: #7353ba; /* accent contrast */
  --color-focus-base: #f7b538; /* focus base */
  --color-disabled-base: #e8e1e5; /* disabled base */
  --color-disabled-contrast: #b9b4b8; /* disabled contrast */
  --color-neutral-default: #b9b4b8; /* neutral default */
  --color-neutral-high-contrast: #8b878a; /* neutral high contrast */
  --color-neutral-low-contrast: #e8e1e5; /* neutral low contrast */
  --color-border-default: #b9b4b8; /* border default */
  --color-border-high-contrast: #8b878a; /* border high contrast */
  --color-border-low-contrast: #d1cbce; /* border low contrast */
  --color-surface-0-default-base: #ffffff;
  --color-surface-0-default-contrast: #2e2c2f;
  --color-surface-1-default-base: #ffffff;
  --color-surface-1-default-contrast: #2e2c2f;
  --color-surface-1-hover-base: #e8e1e5;
  --color-surface-1-hover-contrast: #2e2c2f;
  --color-surface-1-active-base: #e8e1e5;
  --color-surface-1-active-contrast: #2e2c2f;
  --color-surface-2-default-base: #ffffff;
  --color-surface-2-default-contrast: #2e2c2f;
  --color-surface-2-hover-base: #e8e1e5;
  --color-surface-2-hover-contrast: #2e2c2f;
  --color-surface-2-active-base: #e8e1e5;
  --color-surface-2-active-contrast: #2e2c2f;
  --color-surface-3-default-base: #ffffff; /* surface 3 default base */
  --color-surface-3-default-contrast: #2e2c2f; /* surface 3 default contrast */
  --color-surface-3-hover-base: #e8e1e5; /* surface 3 hover base */
  --color-surface-3-hover-contrast: #2e2c2f; /* surface 3 hover contrast */
  --color-surface-3-active-base: #e8e1e5; /* surface 3 active base */
  --color-surface-3-active-contrast: #2e2c2f; /* surface 3 active contrast */
  --color-surface-4-default-base: #ffffff; /* surface 4 default base */
  --color-surface-4-default-contrast: #2e2c2f; /* surface 4 default contrast */
  --color-surface-4-hover-base: #e8e1e5; /* surface 4 hover base */
  --color-surface-4-hover-contrast: #2e2c2f; /* surface 4 hover contrast */
  --color-surface-4-active-base: #e8e1e5; /* surface 4 active base */
  --color-surface-4-active-contrast: #2e2c2f; /* surface 4 active contrast */
  --color-surface-5-default-base: #ffffff; /* surface 5 default base */
  --color-surface-5-default-contrast: #2e2c2f; /* surface 5 default contrast */
  --color-surface-5-hover-base: #e8e1e5; /* surface 5 hover base */
  --color-surface-5-hover-contrast: #2e2c2f; /* surface 5 hover contrast */
  --color-surface-5-active-base: #e8e1e5; /* surface 5 active base */
  --color-surface-5-active-contrast: #2e2c2f; /* surface 5 active contrast */
  --color-support-error-base: #f14c4c; /* support error base */
  --color-support-error-high-ontrast: #990000; /* support error high contrast */
  --color-support-error-low-contrast: #fee5e5; /* support error low contrast */
  --color-support-success-base: #739e41; /* support success base */
  --color-support-success-high-contrast: #3a8340; /* support success high contrast */
  --color-support-success-low-contrast: #f0f8f0; /* support success low contrast */
  --color-support-warning-base: #f2a51a; /* support warning base */
  --color-support-warning-high-contrast: #946f00; /* support warning high contrast */
  --color-support-warning-low-contrast: #fffaeb; /* support warning low contrast */
  --color-support-info-base: #9bc3d3; /* support info base */
  --color-support-info-high-contrast: #257fa4; /* support info high contrast */
  --color-support-info-low-contrast: #f9fcfd; /* support info low contrast */
  --font-link-font-size: 16px;
  --font-link-text-decoration: none;
  --font-link-font-family: Poppins;
  --font-link-font-weight: 700;
  --font-link-font-style: normal;
  --font-link-font-stretch: normal;
  --font-link-font-style-old: Bold;
  --font-link-letter-spacing: 0;
  --font-link-line-height: 24px;
  --font-link-paragraph-indent: 0;
  --font-link-paragraph-spacing: 0;
  --font-link-text-case: none;
  --font-display-lg-font-size: 72px;
  --font-display-lg-text-decoration: none;
  --font-display-lg-font-family: Poppins;
  --font-display-lg-font-weight: 900;
  --font-display-lg-font-style: normal;
  --font-display-lg-font-stretch: normal;
  --font-display-lg-font-style-old: Black;
  --font-display-lg-letter-spacing: 0;
  --font-display-lg-line-height: 80px;
  --font-display-lg-paragraph-indent: 0;
  --font-display-lg-paragraph-spacing: 0;
  --font-display-lg-text-case: none;
  --font-display-sm-font-size: 60px;
  --font-display-sm-text-decoration: none;
  --font-display-sm-font-family: Poppins;
  --font-display-sm-font-weight: 900;
  --font-display-sm-font-style: normal;
  --font-display-sm-font-stretch: normal;
  --font-display-sm-font-style-old: Black;
  --font-display-sm-letter-spacing: 0;
  --font-display-sm-line-height: 58px;
  --font-display-sm-paragraph-indent: 0;
  --font-display-sm-paragraph-spacing: 0;
  --font-display-sm-text-case: none;
  --font-title-lg-font-size: 24px;
  --font-title-lg-text-decoration: none;
  --font-title-lg-font-family: Poppins;
  --font-title-lg-font-weight: 900;
  --font-title-lg-font-style: normal;
  --font-title-lg-font-stretch: normal;
  --font-title-lg-font-style-old: Black;
  --font-title-lg-letter-spacing: 0;
  --font-title-lg-line-height: 28px;
  --font-title-lg-paragraph-indent: 0;
  --font-title-lg-paragraph-spacing: 0;
  --font-title-lg-text-case: none;
  --font-title-md-font-size: 18px;
  --font-title-md-text-decoration: none;
  --font-title-md-font-family: Poppins;
  --font-title-md-font-weight: 700;
  --font-title-md-font-style: normal;
  --font-title-md-font-stretch: normal;
  --font-title-md-font-style-old: Bold;
  --font-title-md-letter-spacing: 0;
  --font-title-md-line-height: 24px;
  --font-title-md-paragraph-indent: 0;
  --font-title-md-paragraph-spacing: 0;
  --font-title-md-text-case: none;
  --font-title-sm-font-size: 18px;
  --font-title-sm-text-decoration: none;
  --font-title-sm-font-family: Poppins;
  --font-title-sm-font-weight: 600;
  --font-title-sm-font-style: normal;
  --font-title-sm-font-stretch: normal;
  --font-title-sm-font-style-old: SemiBold;
  --font-title-sm-letter-spacing: 0;
  --font-title-sm-line-height: 24px;
  --font-title-sm-paragraph-indent: 0;
  --font-title-sm-paragraph-spacing: 0;
  --font-title-sm-text-case: none;
  --font-body-lg-font-size: 18px;
  --font-body-lg-text-decoration: none;
  --font-body-lg-font-family: Poppins;
  --font-body-lg-font-weight: 400;
  --font-body-lg-font-style: normal;
  --font-body-lg-font-stretch: normal;
  --font-body-lg-font-style-old: Regular;
  --font-body-lg-letter-spacing: 0;
  --font-body-lg-line-height: 27px;
  --font-body-lg-paragraph-indent: 0;
  --font-body-lg-paragraph-spacing: 0;
  --font-body-lg-text-case: none;
  --font-body-md-font-size: 16px;
  --font-body-md-text-decoration: none;
  --font-body-md-font-family: Poppins;
  --font-body-md-font-weight: 400;
  --font-body-md-font-style: normal;
  --font-body-md-font-stretch: normal;
  --font-body-md-font-style-old: Regular;
  --font-body-md-letter-spacing: 0;
  --font-body-md-line-height: 24px;
  --font-body-md-paragraph-indent: 0;
  --font-body-md-paragraph-spacing: 0;
  --font-body-md-text-case: none;
  --font-body-sm-font-size: 12px;
  --font-body-sm-text-decoration: none;
  --font-body-sm-font-family: Poppins;
  --font-body-sm-font-weight: 400;
  --font-body-sm-font-style: normal;
  --font-body-sm-font-stretch: normal;
  --font-body-sm-font-style-old: Regular;
  --font-body-sm-letter-spacing: 0;
  --font-body-sm-line-height: 18px;
  --font-body-sm-paragraph-indent: 0;
  --font-body-sm-paragraph-spacing: 0;
  --font-body-sm-text-case: none;
  --font-quote-lg-font-size: 24px;
  --font-quote-lg-text-decoration: none;
  --font-quote-lg-font-family: Poppins;
  --font-quote-lg-font-weight: 400;
  --font-quote-lg-font-style: normal;
  --font-quote-lg-font-stretch: normal;
  --font-quote-lg-font-style-old: Regular;
  --font-quote-lg-letter-spacing: 0;
  --font-quote-lg-line-height: 28px;
  --font-quote-lg-paragraph-indent: 0;
  --font-quote-lg-paragraph-spacing: 0;
  --font-quote-lg-text-case: none;
  --font-quote-md-font-size: 18px;
  --font-quote-md-text-decoration: none;
  --font-quote-md-font-family: Poppins;
  --font-quote-md-font-weight: 400;
  --font-quote-md-font-style: normal;
  --font-quote-md-font-stretch: normal;
  --font-quote-md-font-style-old: Regular;
  --font-quote-md-letter-spacing: 0;
  --font-quote-md-line-height: 24px;
  --font-quote-md-paragraph-indent: 0;
  --font-quote-md-paragraph-spacing: 0;
  --font-quote-md-text-case: none;
  --font-cta-lg-font-size: 16px;
  --font-cta-lg-text-decoration: none;
  --font-cta-lg-font-family: Poppins;
  --font-cta-lg-font-weight: 400;
  --font-cta-lg-font-style: normal;
  --font-cta-lg-font-stretch: normal;
  --font-cta-lg-font-style-old: Regular;
  --font-cta-lg-letter-spacing: 0;
  --font-cta-lg-line-height: 48px;
  --font-cta-lg-paragraph-indent: 0;
  --font-cta-lg-paragraph-spacing: 0;
  --font-cta-lg-text-case: none;
  --font-cta-md-font-size: 16px;
  --font-cta-md-text-decoration: none;
  --font-cta-md-font-family: Poppins;
  --font-cta-md-font-weight: 400;
  --font-cta-md-font-style: normal;
  --font-cta-md-font-stretch: normal;
  --font-cta-md-font-style-old: Regular;
  --font-cta-md-letter-spacing: 0;
  --font-cta-md-line-height: 40px;
  --font-cta-md-paragraph-indent: 0;
  --font-cta-md-paragraph-spacing: 0;
  --font-cta-md-text-case: none;
  --font-cta-sm-font-size: 16px;
  --font-cta-sm-text-decoration: none;
  --font-cta-sm-font-family: Poppins;
  --font-cta-sm-font-weight: 400;
  --font-cta-sm-font-style: normal;
  --font-cta-sm-font-stretch: normal;
  --font-cta-sm-font-style-old: Regular;
  --font-cta-sm-letter-spacing: 0;
  --font-cta-sm-line-height: 32px;
  --font-cta-sm-paragraph-indent: 0;
  --font-cta-sm-paragraph-spacing: 0;
  --font-cta-sm-text-case: none;
}
`;
		